# Generated by Django 5.0.3 on 2024-03-30 05:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_feedback_delete_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='p_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='p_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='p_phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
